### ISSUE TITLE
Issue importing doc

### ISSUE THREAD

**Issue by podviaznikov** [inkandswitch/cambria#4]
When I import doc which has two array items (with a property that has `null`) all works fine:

```
const importedDoc = cambria.importDoc({
        items: [
                { name: 'Peter Johnson', nationality: null },
                // { name: 'Ashley Appleseed', nationality: null },
                { name: 'John Doe', nationality: null }
              ]
    })
```

but if I have 3 items in the array:

```
const importedDoc = cambria.importDoc({
        items: [
                { name: 'Peter Johnson', nationality: null },
                { name: 'Ashley Appleseed', nationality: null },
                { name: 'John Doe', nationality: null }
              ]
    })
```

it fails with error:

```
(node:21691) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at Object.mergeSchemaObjs (.../node_modules/to-json-schema/lib/helpers.js:40:19)
    at .../node_modules/to-json-schema/lib/index.js:93:24
    at Array.reduce (<anonymous>)
    at ToJsonSchema.getCommonArrayItemSchema (...node_modules/to-json-schema/lib/index.js:92:22)

```

Node version: v12.18.3

**Comment by scott-wyatt** [comment]
Bumping above ^^^

I created a Runkit snippet where the same thing happens.

https://runkit.com/embed/p5i1i5yqo6fr

It's related to the postProcessFnc in `importDoc`

**Comment by geoffturk** [comment]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/32190662/226103482-ed7f0cf6-ffa5-4808-87ae-96b9a5e26c91.png">

Comment out line 20 in `src/docs.ts` and recompile (`yarn build`) and it works.

**Comment by michielbdejong** [comment]
I was able to reproduce both the problem and the mitigation. I'm not sure what that line does though, nor what the side-effects of removing it would be.
